name: Automation_localcommit_python
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: automationlocalcommitpython
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-10-31 05:21:23'
pipelines:
  pipelines/Automation_localcommit_python_Pipeline:
    name: Automation_localcommit_python_Pipeline
    description: automation workflow
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-10-31 05:24:19'
    datasets:
      inputs:
      - datasets/test_dataset
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/test_dataset:
    name: test_dataset
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2025-10-31 05:31:23'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2025-10-31 05:31:23'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-10-31 05:21:23'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-10-31T05:21:23.947539Z'
  name: plibMaven
  version: 8.14.0-SNAPSHOT
  createdAt: '2025-10-31T05:21:23.947539Z'
  type: plibMaven
  enabled: true
  entity: Project
- modifiedAt: '2025-10-31T05:22:18.103Z'
  name: ProphecyLibsPython
  version: 2.1.5
  createdAt: '2025-10-31T05:21:23.947539Z'
  type: plibPypi
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
projectDependencies:
  '33':
    projectUID: 33
    projectName: python_project
    repositoryPath: gitUri=http://gitserver:3000/y26UTxfT_team_5/drRIYOax_project_33.git&subPath=
    version: python_project/v4.0.0.0
    isDefault: false
    author: null
    createdAt: '2025-10-31 05:20:55'
  '41':
    projectUID: 41
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/oimECIpO_team_2/OhOf1CSQ_project_41.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-10-31 05:20:55'
  '40':
    projectUID: 40
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/oimECIpO_team_2/OhOf1CSQ_project_40.git&subPath=
    version: 0.2.51
    isDefault: true
    author: null
    createdAt: '2025-10-31 05:20:55'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
